/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TicketSaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyTicket"
      | "createTicket"
      | "getBuyerDetails"
      | "getTicketDetails"
      | "ticketBuyers"
      | "ticketCount"
      | "ticketOffers"
      | "tickets"
      | "userTickets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OfferAccepted"
      | "OfferMade"
      | "TicketCreated"
      | "TicketPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTicket",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketBuyers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ticketOffers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userTickets",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketBuyers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userTickets",
    data: BytesLike
  ): Result;
}

export namespace OfferAcceptedEvent {
  export type InputTuple = [
    ticketId: BigNumberish,
    buyer: AddressLike,
    acceptedPrice: BigNumberish
  ];
  export type OutputTuple = [
    ticketId: bigint,
    buyer: string,
    acceptedPrice: bigint
  ];
  export interface OutputObject {
    ticketId: bigint;
    buyer: string;
    acceptedPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferMadeEvent {
  export type InputTuple = [
    ticketId: BigNumberish,
    buyer: AddressLike,
    offerPrice: BigNumberish
  ];
  export type OutputTuple = [
    ticketId: bigint,
    buyer: string,
    offerPrice: bigint
  ];
  export interface OutputObject {
    ticketId: bigint;
    buyer: string;
    offerPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    seller: AddressLike,
    eventDetails: string,
    price: BigNumberish,
    ticketsAvailable: BigNumberish,
    isNegotiable: boolean
  ];
  export type OutputTuple = [
    id: bigint,
    seller: string,
    eventDetails: string,
    price: bigint,
    ticketsAvailable: bigint,
    isNegotiable: boolean
  ];
  export interface OutputObject {
    id: bigint;
    seller: string;
    eventDetails: string;
    price: bigint;
    ticketsAvailable: bigint;
    isNegotiable: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPurchasedEvent {
  export type InputTuple = [
    id: BigNumberish,
    buyer: AddressLike,
    price: BigNumberish,
    buyerEmail: string,
    buyerPhone: string,
    nftOrImageCID: string
  ];
  export type OutputTuple = [
    id: bigint,
    buyer: string,
    price: bigint,
    buyerEmail: string,
    buyerPhone: string,
    nftOrImageCID: string
  ];
  export interface OutputObject {
    id: bigint;
    buyer: string;
    price: bigint;
    buyerEmail: string;
    buyerPhone: string;
    nftOrImageCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TicketSale extends BaseContract {
  connect(runner?: ContractRunner | null): TicketSale;
  waitForDeployment(): Promise<this>;

  interface: TicketSaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyTicket: TypedContractMethod<
    [
      _ticketId: BigNumberish,
      _buyerEmail: string,
      _buyerPhone: string,
      _nftOrImageCID: string
    ],
    [void],
    "payable"
  >;

  createTicket: TypedContractMethod<
    [
      _eventDetails: string,
      _location: string,
      _price: BigNumberish,
      _ticketsAvailable: BigNumberish,
      _isNegotiable: boolean,
      _minOffer: BigNumberish,
      _sellerEmail: string,
      _imageCID: string,
      _eventLink: string
    ],
    [void],
    "nonpayable"
  >;

  getBuyerDetails: TypedContractMethod<
    [_ticketId: BigNumberish],
    [
      [string, string, string] & {
        buyerEmail: string;
        buyerPhone: string;
        nftOrImageCID: string;
      }
    ],
    "view"
  >;

  getTicketDetails: TypedContractMethod<
    [_ticketId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean,
        string,
        string,
        string
      ] & {
        id: bigint;
        seller: string;
        eventDetails: string;
        location: string;
        price: bigint;
        ticketsAvailable: bigint;
        isNegotiable: boolean;
        minOffer: bigint;
        isSoldOut: boolean;
        imageCID: string;
        eventLink: string;
        sellerEmail: string;
      }
    ],
    "view"
  >;

  ticketBuyers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string] & {
        buyerEmail: string;
        buyerPhone: string;
        nftOrImageCID: string;
      }
    ],
    "view"
  >;

  ticketCount: TypedContractMethod<[], [bigint], "view">;

  ticketOffers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        buyer: string;
        offerPrice: bigint;
        isAccepted: boolean;
      }
    ],
    "view"
  >;

  tickets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean,
        string,
        string,
        string
      ] & {
        id: bigint;
        seller: string;
        eventDetails: string;
        location: string;
        price: bigint;
        ticketsAvailable: bigint;
        isNegotiable: boolean;
        minOffer: bigint;
        isSoldOut: boolean;
        imageCID: string;
        eventLink: string;
        sellerEmail: string;
      }
    ],
    "view"
  >;

  userTickets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyTicket"
  ): TypedContractMethod<
    [
      _ticketId: BigNumberish,
      _buyerEmail: string,
      _buyerPhone: string,
      _nftOrImageCID: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createTicket"
  ): TypedContractMethod<
    [
      _eventDetails: string,
      _location: string,
      _price: BigNumberish,
      _ticketsAvailable: BigNumberish,
      _isNegotiable: boolean,
      _minOffer: BigNumberish,
      _sellerEmail: string,
      _imageCID: string,
      _eventLink: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuyerDetails"
  ): TypedContractMethod<
    [_ticketId: BigNumberish],
    [
      [string, string, string] & {
        buyerEmail: string;
        buyerPhone: string;
        nftOrImageCID: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTicketDetails"
  ): TypedContractMethod<
    [_ticketId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean,
        string,
        string,
        string
      ] & {
        id: bigint;
        seller: string;
        eventDetails: string;
        location: string;
        price: bigint;
        ticketsAvailable: bigint;
        isNegotiable: boolean;
        minOffer: bigint;
        isSoldOut: boolean;
        imageCID: string;
        eventLink: string;
        sellerEmail: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ticketBuyers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string] & {
        buyerEmail: string;
        buyerPhone: string;
        nftOrImageCID: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ticketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ticketOffers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        buyer: string;
        offerPrice: bigint;
        isAccepted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tickets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean,
        string,
        string,
        string
      ] & {
        id: bigint;
        seller: string;
        eventDetails: string;
        location: string;
        price: bigint;
        ticketsAvailable: bigint;
        isNegotiable: boolean;
        minOffer: bigint;
        isSoldOut: boolean;
        imageCID: string;
        eventLink: string;
        sellerEmail: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userTickets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OfferAccepted"
  ): TypedContractEvent<
    OfferAcceptedEvent.InputTuple,
    OfferAcceptedEvent.OutputTuple,
    OfferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "OfferMade"
  ): TypedContractEvent<
    OfferMadeEvent.InputTuple,
    OfferMadeEvent.OutputTuple,
    OfferMadeEvent.OutputObject
  >;
  getEvent(
    key: "TicketCreated"
  ): TypedContractEvent<
    TicketCreatedEvent.InputTuple,
    TicketCreatedEvent.OutputTuple,
    TicketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TicketPurchased"
  ): TypedContractEvent<
    TicketPurchasedEvent.InputTuple,
    TicketPurchasedEvent.OutputTuple,
    TicketPurchasedEvent.OutputObject
  >;

  filters: {
    "OfferAccepted(uint256,address,uint256)": TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;
    OfferAccepted: TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;

    "OfferMade(uint256,address,uint256)": TypedContractEvent<
      OfferMadeEvent.InputTuple,
      OfferMadeEvent.OutputTuple,
      OfferMadeEvent.OutputObject
    >;
    OfferMade: TypedContractEvent<
      OfferMadeEvent.InputTuple,
      OfferMadeEvent.OutputTuple,
      OfferMadeEvent.OutputObject
    >;

    "TicketCreated(uint256,address,string,uint256,uint256,bool)": TypedContractEvent<
      TicketCreatedEvent.InputTuple,
      TicketCreatedEvent.OutputTuple,
      TicketCreatedEvent.OutputObject
    >;
    TicketCreated: TypedContractEvent<
      TicketCreatedEvent.InputTuple,
      TicketCreatedEvent.OutputTuple,
      TicketCreatedEvent.OutputObject
    >;

    "TicketPurchased(uint256,address,uint256,string,string,string)": TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;
    TicketPurchased: TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;
  };
}
